-- Add start and end time to bookings
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS start_time TEXT NOT NULL DEFAULT '10:00';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS end_time TEXT NOT NULL DEFAULT '14:00';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS event_hours NUMERIC(4,1) NOT NULL DEFAULT 4;
